services:
  mysql:
    image: mysql:${MYSQL_VERSION:-8.0}
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-metadesign}
      MYSQL_USER: ${MYSQL_USER:-metadesign}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-metadesign_pass}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-metadesign_root}
    volumes:
      - database_data:/var/lib/mysql:rw

volumes:
  database_data:
